# Generated by Django 4.0.4 on 2023-04-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0002_alter_user_phonenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpost',
            name='image',
            field=models.ImageField(null=True, upload_to='dinner'),
        ),
    ]
